### ISSUE TITLE
ability to only display map

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#125]
although it takes the whole tabs part of plugin away. it would be nice if there was a way to optionally only display the map without the tabbed ui part.

**Comment by radius314** [comment]
Use CSS to hide the tabs.

**Comment by radius314** [comment]
```css
#bmlt-header { display: none; }
#nav-days { display: none; }
.bmlt-page { display: none; }
```

**Comment by radius314** [comment]
nm, it appears as thought this won't work.

**Comment by radius314** [comment]
The change is available in the latest build.  Use the following CSS with it to hide everything but the map.

```css
#bmlt-tabs-table { display:none!important; }
#tabs-content { display:none!important; }
```
